allowBuilds:
  "@fortawesome/fontawesome-free": true
<<<<<<< before updating
  jupyterlab-singleton-provider: true
=======
  "@parcel/watcher": true
>>>>>>> after updating
  unrs-resolver: true

overrides:
  webpack: "5.76.1"
