# Changes here will be overwritten by Copier
_commit: 06be9d8
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: jupyter
add_wiki: false
email: t.paine154@gmail.com
github: timkpaine
project_description: Example of a JupyterLab extension that consumes e.g. a webcomponent
    singleton registered by another extension
project_name: jupyterlab-singleton-consumer
python_version_primary: '3.11'
team: the jupyterlab-singleton-consumer authors
